### ISSUE TITLE
Beautifying the python terminal version

### ISSUE THREAD

**Issue by gugu256** [Anish-M-code/Metadata-Remover#21]
Hi!

I just found this project while scrolling through [up-for-grabs.net](https://up-for-grabs.net) and i think this tool is really cool!
However, one of the only flaws this program has is its command line interface which i don't find very aesthetically pleasing.

But i'm ready to implement this (for the python and maybe the C version later) using special ASCII/Unicode characters and a terminal-coloring font.
So if you want this idea to become a reality, i'm ready to make this happen any time1

Thank you for reading my issue.

**Comment by gugu256** [comment]
Ok, imma start working on it right now

**Comment by gugu256** [comment]
![design](https://github.com/Anish-M-code/Metadata-Remover/assets/136917276/0fbf95e9-bb15-437d-b543-6ba737325817)

 I started working on the project with this design
Is this good ?

**Comment by gugu256** [comment]
![screenshot](https://github.com/Anish-M-code/Metadata-Remover/assets/136917276/04167048-05e7-48cd-97a3-388456e8a95e)

this too, and now i think i'm done!

**Comment by gugu256** [comment]
All right, i think i'm done!

**Comment by gugu256** [comment]
https://github.com/Anish-M-code/Metadata-Remover/pull/23

**Comment by Anish-M-code** [comment]
@gugu256 how did you compile the program correctly in codeblocks? did you change any file encoding i am using default settings and the resulting program doesn't display special unicode characters correctly.

**Comment by gugu256** [comment]
i don't remember, sorry.
